apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ddns-server.fullname" . }}
  labels:
    {{- include "ddns-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ddns-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ddns-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ddns-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistentStorage.dbData.enabled }}
            - name: dbdata
              mountPath: {{ .Values.persistentStorage.dbData.path }}
          {{- end }}
          {{- if .Values.persistentStorage.cacheData.enabled }}
            - name: cachedata
              mountPath: {{ .Values.persistentStorage.cacheData.path }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.exporter.enabled }}
        - name: "{{ .Chart.Name }}-exporter"
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          env:
          {{- range $key, $value := .Values.exporter.env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
          ports:
         - name: metrics
           containerPort: {{ .Values.exporter.port }}
          imagePullPolicy: "{{ .Values.exporter.image.pullPolicy }}"
          resources:
            {{- toYaml .Values.exporter.resources | indent 10 }}
         {{- end }}
      volumes:
      {{- if .Values.persistentStorage.dbData.enabled }}
        - name: dbdata
          persistentVolumeClaim:
            claimName: {{ include "ddns-server.fullname" . }}-dbdata
      {{- end }}
      {{- if .Values.persistentStorage.cacheData.enabled }}
        - name: cachedata
          persistentVolumeClaim:
            claimName: {{ include "ddns-server.fullname" . }}-cachedata
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
