apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddns-server.fullname" . }}
  labels:
    {{- include "ddns-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.web.nodePort }}
      nodePort: {{ .Values.service.web.nodePort }}
      {{- end }}
    - port: {{ .Values.service.dns.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.dns.nodePort }}
      nodePort: {{ .Values.service.dns.nodePort }}
      {{- end }}
    - port: {{ .Values.service.dns.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.dns.nodePort }}
      nodePort: {{ .Values.service.dns.nodePort }}
      {{- end }}
  selector:
    {{- include "ddns-server.selectorLabels" . | nindent 4 }}
