# Default values for prometheusalert.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imagePullSecrets: []
    # - name: "registry-secret"

replicaCount: 1

image:
  repository: registry-prod.cnzhiyuanhui.com:1555/service_components/feiyu563/prometheus-alert:v4.9
  #repository: feiyu563/prometheus-alert:v4.9
  pullPolicy: Always  #IfNotPresent

nameOverride: ""
fullnameOverride: ""

persistentStorage:
  enabled: true
  storageClass: "nfs-client"
  dbData:
    path: /app/db
    accessModes:
    - ReadWriteOnce
    size: 10Gi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: alert.monitoring.com
      pathType: ImplementationSpecific
      paths: ["/"]

  tls:
  - hosts:
    - alert.monitoring.com
    secretName: monitoring-tls

resources: 
  limits:
   cpu: 1000m
   memory: 1024Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
