# Default values for syslog-ng.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
#specify the image
image:
  repository: "balabit/syslog-ng"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "4.3.1"
#define how the syslog-service should be exposed
service:
  # Optional parameters: ClusterIP or NodePort
  type: NodePort
  plain:
    port: 514
    nodePort: 30514 
  gb2312:
    port: 515
    nodePort: 30515

config:
  syslog_ng_conf: |
    @version: 4.3
    @include "scl.conf"
    
    options {
      flush-lines(1000);
      log-fifo-size(20480);
      log-msg-size(204800);
      use-dns(no);
      on-error(fallback-to-string);
    };
        
    source s_network {
      network(
      ip("0.0.0.0")
      port(514)
      transport("udp")
      keep-hostname(yes)
      );
    };
    
    source s_network_gb {
      network(
      ip("0.0.0.0")
      port(515)
      transport("udp")
      encoding("GB2312")
      keep-hostname(yes)
      );
    };
    
    destination d_kafka {
      channel {
        rewrite {
          set("${HOST}"    value(".eventv1.host"));
          set("1"          value(".eventv1.@version"));
          set("${ISODATE}" value(".eventv1.@timestamp") condition("${.eventv1.@timestamp}" eq ""));
          set("${MESSAGE}" value(".eventv1.message")    condition("${.eventv1.message}" eq ""));
          set("${MSG}"     value(".eventv1.message")    condition("${.eventv1.message}" eq ""));
          set("generic"    value(".eventv1.type")       condition("${.eventv1.type}" eq ""));
        };
        destination {
          kafka-c(config(queue.buffering.max.ms("1000"))
                bootstrap-servers("elk-kafka:9092")
                topic("syslog-ng")
                fallback_topic("syslog-ng")
                message("$(format-json --key .eventv1.* --rekey .eventv1.* --shift 9)"));
        };
      };
    };
    
    log {
      source(s_network_gb);
      source(s_network);
      destination(d_kafka);
    };
    
livenessProbe:
  exec:
    command: ["/usr/sbin/syslog-ng-ctl","stats"]
  initialDelaySeconds: 20
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 2

readinessProbe:
  exec:
    command: ["/usr/sbin/syslog-ng-ctl","stats"]
  initialDelaySeconds: 20
  periodSeconds: 15
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 2

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi


nodeSelector: {}

tolerations: []

affinity: {}
